name: notes
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: 2.0.0+3
  path_provider: 2.0.1
  intl: 0.17.0
  flutter_staggered_grid_view: 0.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700